name: docker-compose

on:
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-compose.yml'
      - '**/docker-compose.yml'
      - 'docker/server/Dockerfile'
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/docker-compose.yml'
      - '**/docker-compose.yml'
      - 'docker/server/Dockerfile'

permissions:
  contents: read

jobs:
  pull:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Update docker-compose
        run: |
          curl -SL https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64 -o docker-compose
          chmod a+x docker-compose

      - name: Pull Docker images
        run: ./docker-compose -f docker/docker-compose.yml pull

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Update docker-compose
        run: |
          curl -SL https://github.com/docker/compose/releases/download/v2.15.1/docker-compose-linux-x86_64 -o docker-compose
          chmod a+x docker-compose

      - name: Build Docker images
        run: ./docker-compose -f docker/docker-compose.yml build
