name: shellcheck

on:
  push:
    branches: [ master ]
    paths:
      - '.github/workflows/shellcheck.yml'
      - '**.sh'
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/shellcheck.yml'
      - '**.sh'

permissions:
  contents: read

jobs:
  lint:
    name: shellcheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: shellcheck
        run: |
          find -name "*.sh" | xargs shellcheck
